version: '3'

services:
  app:
    image: service
    build: .
    ports:
      - ${PORT}:${PORT}
    networks:
      - net-custom
    depends_on:
      - postgres
    restart: always
    logging:
      driver: json-file
    volumes:
      - ./logs:/app/logs
      - ./src:/app/src
    environment:
      PORT: ${PORT}

  postgres:
    image: postgres
    build: ./database/
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - net-custom
    restart: always
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: ${PGDATA}

networks:
  net-custom:
    driver: bridge

volumes:
  logs:
  database:
